server:
   servlet:
      context-path: /iusteiman/api/v1
spring:
    h2:
       console.enabled: true
    datasource:
       url: jdbc:postgresql://localhost:5432/iusteimandb
       username: iusteimanuser
       password: VQsujLXMYpBvHrgDtv7wfCqYTQ95VmZqLAH67YJK67vhL7CAycp@WR26dLyKF3zFSVF346
       driverClassName: org.postgresql.Driver
    jpa:
       show-sql: true
       properties:
          hibernate:
             dialect: org.hibernate.dialect.PostgreSQLDialect
             temp:
                use_jdbc_metadata_defaults: false
       hibernate:
          ddl-auto: update