server:
   servlet:
      context-path: /iusteiman/api/v1
spring:
   servlet:
       multipart:
          max-file-size: 1MB
          max-request-size: 1MB
   mail:
       host: smtp.gmail.com
       port: 587
       username: ${SPRING_GMAIL_IUSTE_USERNAME}
       password: ${SPRING_GMAIL_IUSTE_PASSWORD_NORMAL_RUN}
       protocol: smtp
       properties.mail.smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com
   jpa:
       properties:
          hibernate:
             dialect: org.hibernate.dialect.PostgreSQLDialect
             temp:
                use_jdbc_metadata_defaults: false
       hibernate:
          ddl-auto: update
          hibernate:
             generate-ddl: true
             use_sql_comments: true
             format_sql: true
cloudinary:
   cloudname: ${CLOUDINARY_CLOUD_NAME}
   apikey: ${CLOUDINARY_API_KEY}
   apisecret: ${CLOUDINARY_API_SECRET}
---
apisecretkey: ${API_SECRET}

logging:
   level:
      root: INFO
      com.urzaizcoding.iusteimanserver: TRACE

spring:
   config:
      activate:
         on-profile: dev
   h2:
       console.enabled: true
   datasource:
       url: jdbc:postgresql://localhost:5432/iusteimandb
       username: iusteimanuser
       password: iuste
       driverClassName: org.postgresql.Driver
   jpa:
      show-sql: true
      hibernate:
         hibernate:
            show-sql: true


---

logging:
   level:
      root: DEBUG
      com.urzaizcoding.iusteimanserver: INFO

spring:
   config:
      activate:
         on-profile: prod
   h2:
       console.enabled: false
   datasource:
       url: jdbc:postgresql://${SPRING_IUSTEIMAN_DB_HOST}:${SPRING_IUSTEIMAN_DB_PORT}/${SPRING_IUSTEIMAN_DB_NAME}
       username: ${SPRING_IUSTEIMAN_USER}
       password: ${SPRING_IUSTEIMAN_DB_PASS}
       driverClassName: org.postgresql.Driver
   jpa:
      show-sql: false
      hibernate:
         hibernate:
            show-sql: false


       
       